"""time1

Revision ID: 0f2ae74ca018
Revises: 27289ade1a18
Create Date: 2025-04-21 15:42:49.683424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f2ae74ca018'
down_revision: Union[str, None] = '27289ade1a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_feedback_feedback_id', table_name='feedback')
    op.drop_table('feedback')
    op.drop_table('factsaqi')
    op.add_column('measurements', sa.Column('time1', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('measurements', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_unique_constraint(None, 'measurements', ['station_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'measurements', type_='unique')
    op.alter_column('measurements', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('measurements', 'time1')
    op.create_table('factsaqi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fact', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='factsaqi_pkey')
    )
    op.create_table('feedback',
    sa.Column('feedback_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('info', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stars', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='feedback_user_id_fkey'),
    sa.PrimaryKeyConstraint('feedback_id', name='feedback_pkey')
    )
    op.create_index('ix_feedback_feedback_id', 'feedback', ['feedback_id'], unique=False)
    # ### end Alembic commands ###
