"""removed predictionId

Revision ID: 2e143e7b12c2
Revises: e1fe3f1eaeb1
Create Date: 2025-04-05 13:09:54.973069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e143e7b12c2'
down_revision: Union[str, None] = 'e1fe3f1eaeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'nearby_station',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_predictions_prediction_id', table_name='predictions')
    op.create_index(op.f('ix_predictions_station_id'), 'predictions', ['station_id'], unique=False)
    op.drop_column('predictions', 'prediction_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('prediction_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_predictions_station_id'), table_name='predictions')
    op.create_index('ix_predictions_prediction_id', 'predictions', ['prediction_id'], unique=False)
    op.alter_column('predictions', 'nearby_station',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
