"""Add user preferences table

Revision ID: 5f2506a1b0b3
Revises: 1904adf129cc
Create Date: 2025-04-01 00:16:25.922157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f2506a1b0b3'
down_revision: Union[str, None] = '1904adf129cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('pm25', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('pm10', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('no2', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('co', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('so2', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ozone', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_index(op.f('ix_user_preferences_preference_id'), 'user_preferences', ['preference_id'], unique=False)
    op.drop_column('users', 'preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('preferences', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_preferences_preference_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
