"""Add aqi_category to measurements

Revision ID: 695d926f0af1
Revises: 5f2506a1b0b3
Create Date: 2025-04-01 01:03:02.571050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695d926f0af1'
down_revision: Union[str, None] = '5f2506a1b0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('aqi_category', sa.Enum('good', 'moderate', 'unhealthy_sensitive', 'unhealthy', 'very_unhealthy', 'hazardous', name='aqi_category'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'aqi_category')
    # ### end Alembic commands ###
