"""changed few bits for forum

Revision ID: 6e3671295813
Revises: 73fcdd4d531a
Create Date: 2025-04-04 20:23:37.506760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e3671295813'
down_revision: Union[str, None] = '73fcdd4d531a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_parent_comment_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_comment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_parent_comment_id_fkey', 'comments', 'comments', ['parent_comment_id'], ['comment_id'])
    # ### end Alembic commands ###
