"""Add cascade deletes to contributions

Revision ID: 73fcdd4d531a
Revises: fb629f54d8ac
Create Date: 2025-04-01 17:55:15.836266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fcdd4d531a'
down_revision: Union[str, None] = 'fb629f54d8ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualitative_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('additional_info', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['public_contributions.contribution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualitative_contributions_id'), 'qualitative_contributions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qualitative_contributions_id'), table_name='qualitative_contributions')
    op.drop_table('qualitative_contributions')
    # ### end Alembic commands ###
