"""syncing with models

Revision ID: 91efc1bddd65
Revises: 606e2e08cdd3
Create Date: 2025-04-06 01:28:15.447037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91efc1bddd65'
down_revision: Union[str, None] = '606e2e08cdd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('preference_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('pm25', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('pm10', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('no2', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('co', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('so2', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('ozone', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('preference_id')
    )
    op.create_index(op.f('ix_user_preferences_preference_id'), 'user_preferences', ['preference_id'], unique=False)
    op.create_table('qualitative_contributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('additional_info', sa.String(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contribution_id'], ['public_contributions.contribution_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.station_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualitative_contributions_id'), 'qualitative_contributions', ['id'], unique=False)
    op.create_table('user_post_votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.Enum('up', 'down', name='vote_type'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    op.create_table('user_comment_votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.Enum('up', 'down', name='vote_type'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    op.drop_index('ix_factsaqi_id', table_name='factsaqi')
    op.drop_table('factsaqi')
    op.create_index(op.f('ix_aqi_aggregations_aggregation_id'), 'aqi_aggregations', ['aggregation_id'], unique=False)
    op.add_column('comments', sa.Column('parent_comment_id', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.alter_column('comments', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_comments_comment_id'), 'comments', ['comment_id'], unique=False)
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.drop_constraint('comments_user_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment_id'], ['comment_id'])
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['post_id'])
    op.add_column('measurements', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_measurements_measurement_id'), 'measurements', ['measurement_id'], unique=False)
    op.alter_column('notifications', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.alter_column('posts', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_posts_post_id'), 'posts', ['post_id'], unique=False)
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['user_id'])
    op.add_column('predictions', sa.Column('pm25_predicted', sa.ARRAY(sa.DECIMAL(precision=10, scale=4)), nullable=True))
    op.add_column('predictions', sa.Column('pm10_predicted', sa.ARRAY(sa.DECIMAL(precision=10, scale=4)), nullable=True))
    op.add_column('predictions', sa.Column('no2_predicted', sa.ARRAY(sa.DECIMAL(precision=10, scale=4)), nullable=True))
    op.add_column('predictions', sa.Column('co_predicted', sa.ARRAY(sa.DECIMAL(precision=10, scale=4)), nullable=True))
    op.add_column('predictions', sa.Column('so2_predicted', sa.ARRAY(sa.DECIMAL(precision=10, scale=4)), nullable=True))
    op.add_column('predictions', sa.Column('ozone_predicted', sa.ARRAY(sa.DECIMAL(precision=10, scale=4)), nullable=True))
    op.add_column('predictions', sa.Column('aqi_predicted', sa.ARRAY(sa.Integer()), nullable=True))
    op.add_column('predictions', sa.Column('nearby_station', sa.String(), nullable=False))
    op.alter_column('predictions', 'prediction_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.create_index(op.f('ix_predictions_station_id'), 'predictions', ['station_id'], unique=False)
    op.drop_constraint('predictions_station_id_fkey', 'predictions', type_='foreignkey')
    op.drop_column('predictions', 'predicted_value')
    op.drop_column('predictions', 'confidence')
    op.drop_column('predictions', 'predicted_aqi')
    op.drop_column('predictions', 'prediction_id')
    op.alter_column('public_contributions', 'additional_info',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_public_contributions_contribution_id'), 'public_contributions', ['contribution_id'], unique=False)
    op.drop_constraint('fk_public_contributions_station', 'public_contributions', type_='foreignkey')
    op.drop_constraint('fk_public_contributions_user', 'public_contributions', type_='foreignkey')
    op.alter_column('reports', 'reason',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=False)
    op.drop_constraint('reports_reported_user_id_fkey', 'reports', type_='foreignkey')
    op.drop_constraint('reports_reporter_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['reported_user_id'], ['user_id'])
    op.create_foreign_key(None, 'reports', 'users', ['reporter_id'], ['user_id'])
    op.alter_column('stations', 'station_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.create_index(op.f('ix_stations_station_id'), 'stations', ['station_id'], unique=False)
    op.alter_column('system_logs', 'message',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_system_logs_log_id'), 'system_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_user_reputation_reputation_id'), 'user_reputation', ['reputation_id'], unique=False)
    op.drop_constraint('user_reputation_user_id_fkey', 'user_reputation', type_='foreignkey')
    op.create_foreign_key(None, 'user_reputation', 'users', ['user_id'], ['user_id'])
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.drop_column('users', 'preferences')
    op.create_index(op.f('ix_weather_conditions_weather_id'), 'weather_conditions', ['weather_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_conditions_weather_id'), table_name='weather_conditions')
    op.add_column('users', sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_constraint(None, 'user_reputation', type_='foreignkey')
    op.create_foreign_key('user_reputation_user_id_fkey', 'user_reputation', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_reputation_reputation_id'), table_name='user_reputation')
    op.drop_index(op.f('ix_system_logs_log_id'), table_name='system_logs')
    op.alter_column('system_logs', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_stations_station_id'), table_name='stations')
    op.alter_column('stations', 'station_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_reporter_id_fkey', 'reports', 'users', ['reporter_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('reports_reported_user_id_fkey', 'reports', 'users', ['reported_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.alter_column('reports', 'reason',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_foreign_key('fk_public_contributions_user', 'public_contributions', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('fk_public_contributions_station', 'public_contributions', 'stations', ['station_id'], ['station_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_public_contributions_contribution_id'), table_name='public_contributions')
    op.alter_column('public_contributions', 'additional_info',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('predictions', sa.Column('prediction_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('predictions', sa.Column('predicted_aqi', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('confidence', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=True))
    op.add_column('predictions', sa.Column('predicted_value', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=False))
    op.create_foreign_key('predictions_station_id_fkey', 'predictions', 'stations', ['station_id'], ['station_id'])
    op.drop_index(op.f('ix_predictions_station_id'), table_name='predictions')
    op.alter_column('predictions', 'prediction_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('predictions', 'nearby_station')
    op.drop_column('predictions', 'aqi_predicted')
    op.drop_column('predictions', 'ozone_predicted')
    op.drop_column('predictions', 'so2_predicted')
    op.drop_column('predictions', 'co_predicted')
    op.drop_column('predictions', 'no2_predicted')
    op.drop_column('predictions', 'pm10_predicted')
    op.drop_column('predictions', 'pm25_predicted')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_posts_post_id'), table_name='posts')
    op.alter_column('posts', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.alter_column('notifications', 'message',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_measurements_measurement_id'), table_name='measurements')
    op.drop_column('measurements', 'created_at')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_user_id_fkey', 'comments', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_comments_comment_id'), table_name='comments')
    op.alter_column('comments', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('comments', 'downvotes')
    op.drop_column('comments', 'parent_comment_id')
    op.drop_index(op.f('ix_aqi_aggregations_aggregation_id'), table_name='aqi_aggregations')
    op.create_table('factsaqi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fact', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='factsaqi_pkey')
    )
    op.create_index('ix_factsaqi_id', 'factsaqi', ['id'], unique=False)
    op.drop_table('user_comment_votes')
    op.drop_table('user_post_votes')
    op.drop_index(op.f('ix_qualitative_contributions_id'), table_name='qualitative_contributions')
    op.drop_table('qualitative_contributions')
    op.drop_index(op.f('ix_user_preferences_preference_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
