"""kept parent_comment_id in comment

Revision ID: dc7174f3c9cf
Revises: 6e3671295813
Create Date: 2025-04-04 20:30:00.364257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc7174f3c9cf'
down_revision: Union[str, None] = '6e3671295813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_factsaqi_id', table_name='factsaqi')
    op.drop_table('factsaqi')
    op.add_column('comments', sa.Column('parent_comment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_comment_id'], ['comment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_comment_id')
    op.create_table('factsaqi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fact', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='factsaqi_pkey')
    )
    op.create_index('ix_factsaqi_id', 'factsaqi', ['id'], unique=False)
    # ### end Alembic commands ###
