"""remove aqi_category from measurements

Revision ID: fb629f54d8ac
Revises: 695d926f0af1
Create Date: 2025-04-01 11:06:21.965865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb629f54d8ac'
down_revision: Union[str, None] = '695d926f0af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurements', 'aqi_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('aqi_category', postgresql.ENUM('good', 'moderate', 'unhealthy_sensitive', 'unhealthy', 'very_unhealthy', 'hazardous', name='aqi_category'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
